STOP_WORDS = [  # words to be removed from the text
    "of",
    "the",
    "at",
    "family",
    "keeper",
    "wizard",
    "fat",
    "de",
    "hogwarts",
    "hotel",
    "owner",
    "express",
    "and",
    "witch",
    "who",
    "Senior",
    "Junior",
]

# Character titles with these words will not be matched
REMOVE_WORDS = [
    "wizard",
    "Wizard",
    "witch",
    "Witch",
    "director",
    "at",
    "of",
    "owner",
    "family",
    "Unidentified",
    "conductor",
    "Goblin",
    "Squid",
    "ghoul",
    "and",
    "Salamander",
    "ghost",
    "Ghost",
    "Transylvania",
    "colony",
    "saleswoman",
    "Dementor",
    "herd",
    "Boggart",
    "Troll",
    "Hangleton",
    "House",
    "Academy",
    "postman",
    "Omnioculars",
    "Veela",
    "children",
    "Hogwarts",
    "Sisters",
    "sisters",
    "Unicorn",
    "Lake",
    "Maze",
    "Place",
    "Nottingham",
    "Girl",
    "Member",
    "Inferius",
    "official",
    "peacock",
    "boy",
    "cat",
    "Department",
    "woman",
    "brothers",
    "Wandless",
    # words with "'" such as "Piers Polkiss's mother"
]

SHORT_FORMS = {
    "Ronald": "ron",
    "William": "bill",
    "Charles": "charlie",
    "Percy": "perce",
    "Ginevra": "ginny",
    "Ludovic": "ludo",
    "Bartemius": "barty",
    "Reginald": "reg",
}


# {book-chapter: {span: [hardcoded_options]}}
CHAPTER_HARDCODED_OPTIONS = {
    "7-37": {
        "James": ["James Potter II"],
        "Albus": ["Albus Potter"],
        "Rose": ["Rose Granger-Weasley"],
    }
}
